-- 리드(견적 문의)
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  client_name text not null,
  phone text not null,
  email text not null,
  message text default '',
  business_type text not null,
  area text not null,
  budget text not null,
  estimate_min int,
  estimate_max int,
  status text not null default '신규',
  created_at timestamptz default now()
);

-- 포트폴리오
create table if not exists public.portfolios (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  area text not null,
  budget text not null,
  industry text not null,
  style text not null,
  duration text not null,
  image_url text not null,
  created_at timestamptz default now()
);

-- 리뷰 (선택, 랜딩용)
create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  name text not null,
  business text not null,
  rating int not null default 5,
  comment text not null,
  image text not null,
  created_at timestamptz default now()
);

-- RLS: 공개 읽기, 인증된 사용자만 쓰기 (관리자만 수정하려면 나중에 Auth 연동)
alter table public.leads enable row level security;
alter table public.portfolios enable row level security;
alter table public.reviews enable row level security;

create policy "leads read" on public.leads for select using (true);
create policy "leads insert" on public.leads for insert with check (true);
create policy "leads update" on public.leads for update using (true);

create policy "portfolios read" on public.portfolios for select using (true);
create policy "portfolios insert" on public.portfolios for insert with check (true);
create policy "portfolios update" on public.portfolios for update using (true);
create policy "portfolios delete" on public.portfolios for delete using (true);

create policy "reviews read" on public.reviews for select using (true);
create policy "reviews insert" on public.reviews for insert with check (true);
